name: continuous-integration

on: [push, pull_request]

jobs:
  CI:
    name: continuous-integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn cache clean --all && yarn install --nonInteractive --frozen-lockfile

      - name: Lint
        run: yarn run lint:ci

      - name: Build
        run: yarn run build
